apiVersion: v1
name: mc-router
version: 1.5.0
# not used
appVersion: 1.0.0
home: https://git.farh.net/farhoodliquor/minecraft-server-charts
description: Routes Minecraft client connections to backend servers based upon the requested server address.
keywords:
  - minecraft
  - router
sources:
  - https://git.farh.net/farhoodliquor/minecraft-server-charts/tree/master/charts/mc-router
maintainers:
  - name: gtaylor
    email: gtaylor@gc-taylor.com
  - name: billimek
    email: jeff@billimek.com
  - name: itzg
    email: itzgeoff@gmail.com
  - name: bibz87
    email: yannik@carbongem.com
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/itzg/mc-router
    - name: Image DockerHub
      url: https://hub.docker.com/r/itzg/mc-router
