apiVersion: v1
name: minecraft
version: 5.2.0
appVersion: 1.20.1
home: https://minecraft.net/
description: Minecraft server
keywords:
  - game
  - server
sources:
  - https://git.farh.net/farhoodliquor/minecraft-server-charts
maintainers:
  - name: gtaylor
    email: gtaylor@gc-taylor.com
  - name: billimek
    email: jeff@billimek.com
  - name: itzg
    email: itzgeoff@gmail.com
  - name: bibz87
    email: yannik@carbongem.com
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/itzg/docker-minecraft-server
    - name: Image DockerHub
      url: https://hub.docker.com/r/itzg/minecraft-server
