{{- if and .Values.persistence.dataDir.enabled (not .Values.persistence.dataDir.existingClaim ) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "proxy.fullname" . }}-datadir
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "proxy.fullname" . }}
    chart: "{{ include "chart.fullname" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataDir.Size | quote }}
{{- $sc := .Values.persistence.dataDir.storageClass | default .Values.persistence.storageClass | default "" }}
{{- if $sc }}
{{- if (eq "-" $sc) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ $sc | quote }}
{{- end }}
{{- end }}
{{- end -}}
