{{- if and .Values.mcbackup.persistence.backupDir.enabled (not .Values.mcbackup.persistence.backupDir.existingClaim ) (not .Values.workloadAsStatefulSet) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "minecraft.fullname" . }}-backupdir
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: {{ template "chart.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: {{ template "minecraft.fullname" . }}
    app.kubernetes.io/version: {{ template "chart.version" . }}
  {{- with .Values.mcbackup.persistence.annotations  }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{ .Values.mcbackup.persistence.backupDir.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mcbackup.persistence.backupDir.Size | quote }}
{{- $sc := .Values.mcbackup.persistence.backupDir.storageClass | default .Values.mcbackup.persistence.storageClass | default "" }}
{{- if $sc }}
{{- if (eq "-" $sc) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ $sc | quote }}
{{- end }}
{{- end }}
{{- end -}}
